### ISSUE TITLE
TrimGalore download path

### ISSUE THREAD

**Issue by SophieS9** [guyleonard/evomics_2017#18]
Now hosted on github and file structure changed so this file - /genomics/software_tasks/trim_galore.yaml - needs to be updated to:

```
- name: Download Trim Galore! {{version}}
  get_url: url="https://github.com/FelixKrueger/TrimGalore/archive/{{version}}.zip" dest={{source_dir}}/trim_galore_v{{version}}.zip

- name: Unzip Trim Galore!
  unarchive:
    src: "{{source_dir}}/trim_galore_v{{version}}.zip"
    dest: "{{software_dir}}"
    copy: no
    creates: "{{software_dir}}/trim_galore_zip"

- name: Install Trim Galore!
  file: src="{{software_dir}}/TrimGalore-{{version}}/trim_galore" dest=/usr/local/bin/trim_galore state=link
```
